// Suíte do fallback de nome pelo PRIMEIRO PROMPT (v0.4.1).
//
// Defeito original, medido em 2026-08-29: o índice só sabia casar a aba pelo título
// gravado no transcript (`ai-title` / `custom-title`). Duas sessões novas abertas no mesmo
// dia ficaram HORAS com ZERO ocorrência de `"type":"ai-title"` no .jsonl — e sem título o
// painel nunca resolve: fica no placeholder e o botão "editar" responde "não consegui
// identificar a sessão desta aba ainda". O "ainda" mentia: não era transitório.
//
// O harness já documentava a premissa que quebrou, em `transcriptNoTitle`:
// "medido: ~65 s até o Claude Code gravar o ai-title".
//
// Correção: quando não há título nenhum, o nome sai do primeiro prompt do usuário — que é
// exatamente de onde o Claude Code tira o label da aba (conferido nas sessões reais:
// prompt "bora2" → aba "bora2").

const h = require("./harness.js");
const {
  ext, mem, state, ok, section, boot, focus, claudeTab,
  transcript, transcriptNoTitle, transcriptFirstPrompt, transcriptFirstPromptBlocos,
  appendTitle, appendCustomTitle, noteBody, settle, wait, lastPosted,
  LAPSO, PROJECTS_DIR,
} = h;

async function run() {
  // ================= BLOCO P — o fallback resolve a sessão anônima =================

  section("[P1] Sessão SEM título nenhum resolve pelo primeiro prompt");
  {
    await boot();
    transcriptFirstPrompt("sP1", "bora2");
    mem.write(LAPSO + "/sP1.md", noteBody("MONTANDO O PLANO", "notas"));
    await focus(claudeTab("bora2"));
    ok(
      lastPosted("update")?.sessionId === "sP1",
      "aba 'bora2' casa com a sessão cujo primeiro prompt é 'bora2' (antes: unresolved pra sempre)"
    );
    ok(
      !state.posted.some((m) => m.type === "unresolved"),
      "não cai no placeholder — o defeito original"
    );
  }

  section("[P2] O envelope que vem ANTES do prompt não vira nome da sessão");
  {
    await boot();
    // Exatamente o que o Claude Code grava antes do primeiro prompt de verdade.
    transcriptFirstPrompt("sP2", "bora2", [
      "<system-reminder>\nAs you answer the user's questions...\n</system-reminder>",
      "Caveat: The messages below were generated by the user while running local commands.",
      "<command-name>/clear</command-name>",
    ]);
    mem.write(LAPSO + "/sP2.md", noteBody("S", "n"));
    await focus(claudeTab("bora2"));
    ok(
      lastPosted("update")?.sessionId === "sP2",
      "system-reminder, caveat e <command-name> são pulados — o nome é o prompt de verdade"
    );
  }

  section("[P3] Prompt gravado em BLOCOS (a outra forma do transcript) também serve");
  {
    await boot();
    transcriptFirstPromptBlocos("sP3", "arrumar o painel");
    mem.write(LAPSO + "/sP3.md", noteBody("S", "n"));
    await focus(claudeTab("arrumar o painel"));
    ok(
      lastPosted("update")?.sessionId === "sP3",
      "content como array de blocos de texto é lido igual ao content string"
    );
  }

  section("[P4] Prompt de várias linhas casa com o label de UMA linha");
  {
    await boot();
    transcriptFirstPrompt("sP4", "arrumar o painel\ne depois rodar os testes");
    mem.write(LAPSO + "/sP4.md", noteBody("S", "n"));
    await focus(claudeTab("arrumar o painel"));
    ok(
      lastPosted("update")?.sessionId === "sP4",
      "só a primeira linha vira nome — a aba nunca mostra quebra de linha"
    );
  }

  section("[P5] Prompt longo casa com o label TRUNCADO pela aba");
  {
    await boot();
    transcriptFirstPrompt(
      "sP5",
      "aqui vamos fazer um app simples para funcionar via linha de comando"
    );
    mem.write(LAPSO + "/sP5.md", noteBody("S", "n"));
    await focus(claudeTab("aqui vamos fazer um app simples…"));
    ok(
      lastPosted("update")?.sessionId === "sP5",
      "a régua de truncamento que já existia vale igual pro fallback"
    );
  }

  // ================= BLOCO Q — o fallback NUNCA atropela um título =================

  section("[Q1] ai-title vence o primeiro prompt");
  {
    await boot();
    transcriptFirstPrompt("sQ1", "bora2");
    appendTitle("sQ1", "Montar a especificação do detector");
    mem.write(LAPSO + "/sQ1.md", noteBody("S", "n"));

    await focus(claudeTab("Montar a especificação do detector"));
    ok(
      lastPosted("update")?.sessionId === "sQ1",
      "com ai-title gravado, o nome da sessão é ele — o fallback sai de cena"
    );

    state.posted.length = 0;
    await focus(h.fileTab("outro.ts"));
    await focus(claudeTab("bora2"));
    ok(
      !state.posted.some((m) => m.type === "update" && m.sessionId === "sQ1"),
      "o primeiro prompt NÃO continua valendo como nome depois do ai-title (senão a sessão teria dois nomes)"
    );
  }

  section("[Q2] custom-title (o nome que o dono deu) vence o ai-title");
  {
    await boot();
    transcriptFirstPrompt("sQ2", "bora2");
    appendTitle("sQ2", "Nome gerado pela IA");
    appendCustomTitle("sQ2", "Nome que eu escolhi");
    mem.write(LAPSO + "/sQ2.md", noteBody("S", "n"));
    await focus(claudeTab("Nome que eu escolhi"));
    ok(
      lastPosted("update")?.sessionId === "sQ2",
      "precedência preservada: custom > ai > primeiro prompt"
    );
  }

  section("[Q3] Transcript sem prompt nenhum continua não identificado");
  {
    await boot();
    transcriptNoTitle("sQ3");
    mem.write(LAPSO + "/sQ3.md", noteBody("S", "n"));
    await focus(claudeTab("Sessão sem nada"));
    ok(
      lastPosted()?.type === "unresolved",
      "sem título E sem prompt, segue não identificada — o fallback não inventa nome"
    );
  }

  section("[Q4] Duas sessões anônimas: cada aba pega a SUA, não a mais recente");
  {
    await boot();
    transcriptFirstPrompt("sQ4a", "bora2");
    transcriptFirstPrompt("sQ4b", "oi");
    mem.write(LAPSO + "/sQ4a.md", noteBody("NOTA DO BORA2", "n"));
    mem.write(LAPSO + "/sQ4b.md", noteBody("NOTA DO OI", "n"));

    await focus(claudeTab("oi"));
    ok(
      lastPosted("update")?.sessionId === "sQ4b",
      "aba 'oi' pega a sessão 'oi' (um fallback por 'sessão mais recente' erraria aqui)"
    );
    await focus(h.fileTab("x.ts"));
    await focus(claudeTab("bora2"));
    ok(
      lastPosted("update")?.sessionId === "sQ4a",
      "aba 'bora2' pega a sessão 'bora2' — duas sessões anônimas convivem sem trocar de nota"
    );
  }

  // ================= BLOCO R — a sessão VIVA não fica relendo a cabeça =================

  section("[R1] Sessão anônima que cresce continua resolvida (o prompt fica no cache)");
  {
    await boot();
    transcriptFirstPrompt("sR1", "bora2");
    mem.write(LAPSO + "/sR1.md", noteBody("S", "n"));
    const aba = claudeTab("bora2");
    await focus(aba);
    ok(lastPosted("update")?.sessionId === "sR1", "resolvida na primeira vez");

    // A sessão viva só cresce na CAUDA — o primeiro prompt segue lá atrás, na cabeça.
    const chave = PROJECTS_DIR + "/sR1.jsonl";
    mem.write(
      chave,
      (mem.read(chave) ?? "") +
        JSON.stringify({ type: "assistant", sessionId: "sR1", pad: "y".repeat(200) }) + "\n"
    );
    state.posted.length = 0;
    h.fireTabs({ opened: [], closed: [], changed: [aba] });
    await settle(60);
    ok(
      !state.posted.some((m) => m.type === "unresolved"),
      "crescer o transcript não faz a sessão anônima perder o nome"
    );
  }

  h.finish();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
